language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

dist: trusty

sudo: false

before_script:
  - (composer self-update; true)
  - composer install

script:
  - composer test

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
    fi
